app = 'sverige-news'
primary_region = 'arn'

[build]

[[mounts]]
source = 'data'
destination = '/data'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = 'shared-cpu-1x'
cpus = 1
memory_mb = 256
